trigger:
- none

pool:
  vmImage: ubuntu-latest
  
variables: 
  logicAppEndPoint: 
  siteName:
  siteUrl:

steps:
- task: AzureCLI@2
  name: CreateInvite
  inputs:
    azureSubscription: ''
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=invitationUrl]$(az staticwebapp users invite -n $(siteName) --authentication-provider AAD --user-details $(userEmail) --role Contributor --domain $(siteUrl) --invitation-expiration-in-hours 168 --query  'invitationUrl')"
- script: |
      env | sort
      REQUEST=$(curl --location --request POST $(logicAppEndPoint) --header 'Content-Type: application/json' --data-raw '{ "email": '\"$USEREMAIL\"', "invitationUrl": '$INVITATIONURL'}')
      echo $REQUEST
  name: TriggerLogicApp